version: '3.5'

services:
  api:
    container_name: nest_api
    env_file: './.env'
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    volumes:
      - ./:/var/www/application/
    environment:
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:13
    container_name: 'postgres'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
