server:
  PORT: 3000
  root: &root http://localhost

db:
  type: postgres
  host: db
  port: 5432
  username: postgres
  password: postgres
  database: nestDB
  synchronize: true
  migrationsRun: false
  logging: true

graphql:
  debug: true
  playground: true
  introspection: true
